blank_issues_enabled: false
contact_links:
  - name: Snowflake community on Discord
    url: https://discord.gg/n8tGJ6Rn6D
    about: Please ask and answer questions here.
  - name: Snowflake community on Matrix
    url: https://matrix.to/#/#snowflake-editor:matrix.org
    about: Please ask and answer questions here.
  - name: Snowflake documentation
    url: https://docs.snowflake.dev/
    about: Documentation for Snowflake
